[package]
name = "my_2d_shooter"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.11" 
bevy_prototype_lyon = "0.6" 
tokio = { version = "1.32", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
noise = "0.9"